# Generated by Django 5.1 on 2024-08-26 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='imagen',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.artista'),
        ),
    ]
