# Generated by Django 5.1 on 2024-08-26 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_artista_imagen_alter_cancion_artista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to='blog.artista'),
        ),
    ]
