# Generated by Django 5.1 on 2024-08-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_genero_alter_publicacion_descripcion_album_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genero',
            name='descripcion',
        ),
    ]
