# Generated by Django 5.1 on 2024-08-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_genero_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='link_facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artista',
            name='link_instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artista',
            name='link_tiktok',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artista',
            name='link_twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
