# Generated by Django 5.1 on 2024-08-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_favorito_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='album',
            name='cantidad_canciones',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='canciones', to='blog.categoria'),
        ),
        migrations.RemoveField(
            model_name='cancion',
            name='genero',
        ),
        migrations.AddField(
            model_name='cancion',
            name='genero',
            field=models.ManyToManyField(blank=True, related_name='canciones', to='blog.genero'),
        ),
    ]
