# Generated by Django 5.1 on 2024-08-30 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_album_descripcion_album_cantidad_canciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='letras',
            field=models.CharField(default='default_value', max_length=255),
        ),
    ]
