# Generated by Django 5.1 on 2024-08-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_intentoiniciosesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='letras',
            field=models.CharField(max_length=255),
        ),
    ]
