# Generated by Django 5.1 on 2024-08-31 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_cancion_letras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='letras',
            field=models.CharField(max_length=255),
        ),
    ]
