# Generated by Django 5.1 on 2024-08-31 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_cancion_letras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='letras',
            field=models.TextField(),
        ),
    ]
