# Generated by Django 5.1 on 2024-08-31 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_cancion_letras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='letras',
            field=models.TextField(verbose_name='lyrics'),
        ),
    ]
